### ISSUE TITLE
Wrong information about getting the bpm.war

### ISSUE THREAD

**Issue by ugreen** [bloomreach/docs-feedback#1]
https://documentation.bloomreach.com/12/library/enterprise/enterprise-features/workflow-process-management/package-wpm-with-separate-authoring-and-delivery-distributions.html
Step 3.1
I think it should be something like:
```
    <dependencySet>
      <useProjectArtifact>false</useProjectArtifact>
      <outputDirectory>webapps</outputDirectory>
      <outputFileNameMapping>bpm.war</outputFileNameMapping>
      <scope>provided</scope>
      <includes>
        <include>com.onehippo.cms7:hippo-addon-wpm-camunda:war</include>
      </includes>
    </dependencySet>
```

**Comment by nvankampenhout** [comment]
Thanks for your feedback! We'll look into this ASAP and report back here.

**Comment by nvankampenhout** [comment]
Hi Ulrich,

This is now fixed in https://documentation.bloomreach.com/12/library/enterprise/enterprise-features/workflow-process-management/package-wpm-with-separate-authoring-and-delivery-distributions.html.

Thanks again!
Niels
