### ISSUE TITLE
wrong mysql connector

### ISSUE THREAD

**Issue by JasperFloorBloomreach** [bloomreach/docs-feedback#10]
https://documentation.bloomreach.com/library/enterprise/installation-and-configuration/linux-installation-manual.html.

The page says to download this jar:
mysql-connector-java-5.1.40.jar

but the child page on mysql says to use  com.mysql.cj.jdbc.Driver. This driver is not available in that jar. IT either should download a newer connector (most best) or the mysql page should mention using com.mysql.jdbc.Driver. Note that  com.mysql.cj.jdbc.Driver is the newer driver. Perhaps check with infra or engineering on this point as to what is preferred.

Alternatively, this page is supposed to be more generic than the child pages on specific database. Perhaps remove the specific jar altogether and replace with a placeholder...but they are currently meant to be copied as shell commands, which won't work with a placeholder

**Comment by nvankampenhout** [comment]
Bumped MySQL version to 8.0.19.
