### ISSUE TITLE
Documentation about custom validation fields missing information to make it work

### ISSUE THREAD

**Issue by CB-Joris** [bloomreach/docs-feedback#100]
https://xmdocumentation.bloomreach.com/library/concepts/plugins/create-a-custom-field-validator.html

Above steps will not work withoud adding the validation id to the editor template in the yaml file. Took us 2 days to find out so please add this on this page.

`         frontend:references: [ wicket.model, model.compareTo, engine, validator.id ]`
`          frontend:services: [ wicket.id, validator.id ]`

[full_yaml_file.txt](https://github.com/bloomreach/docs-feedback/files/8823072/full_yaml_file.txt)

Please add this to the documentation to help people in the future.

**Comment by nvankampenhout** [comment]
Thanks for the feedback and apologies for the missing info @CB-Joris , we'll try to pick this up asap.

**Comment by nvankampenhout** [comment]
I verified and confirmed this issue and added a "Troubleshooting" paragraph to the documentation page:

https://xmdocumentation.bloomreach.com/library/concepts/plugins/create-a-custom-field-validator.html#Troubleshooting
