### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by maxgda** [bloomreach/docs-feedback#102]
https://xmdocumentation.bloomreach.com/library/concepts/web-application/jcr-session-pooling-repository.html

Session pools can be evicted if they **are used any more**. 
Session pools can be evicted if they **are _not_ used any more**. 

![image](https://user-images.githubusercontent.com/28898268/172841140-f8a57b39-61e9-4146-bb77-6c0a31449b48.png)

**Comment by nvankampenhout** [comment]
Fixed, thanks for reporting!
