### ISSUE TITLE
Improve the solution of the screenshot

### ISSUE THREAD

**Issue by MPriess** [bloomreach/docs-feedback#105]
The attached screenshot on the page has a low resolution.

https://xmdocumentation.bloomreach.com/library/concepts/plugins/seo-support/about.html

**Comment by nvankampenhout** [comment]
Thanks, it's a known issue with the site, the frontend automatically uses a scaled-down version of the image. As a workaround I linked the image to a larger size so it opens if you click on it. Hope this helps.
