### ISSUE TITLE
The url of the SDK points to an outdated example

### ISSUE THREAD

**Issue by maxgda** [bloomreach/docs-feedback#106]
https://xmdocumentation.bloomreach.com/library/concepts/spa-integration/sdks.html

https://github.com/bloomreach/brxm/tree/brxm-14.5.0-1/spa-sdk/examples.
should be:
https://github.com/bloomreach/spa-sdk/tree/main/examples/

**Comment by nvankampenhout** [comment]
Thanks for reporting, the link has been fixed.
