### ISSUE TITLE
Add a link to the rest services setup guide

### ISSUE THREAD

**Issue by matsodolphijkvk** [bloomreach/docs-feedback#108]
Hi there,

Article: https://xmdocumentation.bloomreach.com/library/concepts/rest/content-rest-api/document-collection-resource.html

This article contains the following text:

"After running the REST setup tool and adding the generic resources using the default settings, this resource can be found in your local project at:"

It would be helpfull to add a link to the installation guide: https://xmdocumentation.bloomreach.com/library/setup/development-tools.html#rest-services-setup.

Kind regards,

Mats

**Comment by nvankampenhout** [comment]
Hi @matsodolphijkvk, thanks for your feedback! I added the link as you suggested.
