### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by MPriess** [bloomreach/docs-feedback#109]
Seems like the URL http://cdn.rawgit.com/paultuckey/urlrewritefilter/master/src/doc/manual/4.0/index.html is broken.

https://xmdocumentation.bloomreach.com/library/enterprise/enterprise-features/url-rewriter/xml-rule.html

**Comment by nvankampenhout** [comment]
Thanks! I updated the link to point to https://tuckey.org/urlrewrite/manual/4.0/index.html.
