### ISSUE TITLE
Typo under the "Limit your queries" heading

### ISSUE THREAD

**Issue by ziga-solar** [bloomreach/docs-feedback#11]
On page https://documentation.bloomreach.com/library/setup/best-practices.html under the "Limit your queries" heading there is a typo. 

Bolded the typo

The generic HST components provided by **he** setup application implement the use of such limits by calling the org.hippoecm.hst.content.beans.query.HstQuery#setLimit() function.

**Comment by nvankampenhout** [comment]
Fixed, thanks!
