### ISSUE TITLE
Configure pinger interval example seems to be incorrect

### ISSUE THREAD

**Issue by matsodolphijkvk** [bloomreach/docs-feedback#110]
A suggestion for article: https://xmdocumentation.bloomreach.com/library/concepts/editor-interface/set-timeouts-and-parameterize-refresh-intervals.html

The example of setting a custom pinger interval with value '90' will result in a warning message. My log snippet:

[INFO] [talledLocalContainer] 31.10.2022 15:20:25 WARN  http-nio-8080-exec-9 [DurationUtils.parse:49] Failed to parse '90' as a java.time.Duration.
[INFO] [talledLocalContainer] Note: since Wicket 9 durations are parsed by java.time.Duration.parse() instead of org.apache.wicket.util.time.Duration.valueOf(). The input formats accepted are based on the ISO-8601 duration format PnDTnHnMn.nS with days considered to be exactly 24 hours.
[INFO] [talledLocalContainer] Users are encouraged to update their duration(s) to the new format. For backwards compatibility we will try to parse it using the 'deprecated' format.

A good custom pinger interval would be something like this: PT1M, which is 1 minute. 

My source: https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-

I haven't tested this with a new installation from an archetype, so I hope im not just wasting your time.

Kind regards,

Mats

**Comment by nvankampenhout** [comment]
Thanks for the heads-up @matsodolphijkvk . This page should have been updated when brXM 15.0 was released. I confirmed with a fresh v15 archetype project and updated the page.

FWIW, there is some background info on this in the v14 to v15 upgrade docs: https://xmdocumentation.bloomreach.com/library/upgrade-14-to-15/steps/upgrade-to-wicket-9.html

Thanks,
Niels
