### ISSUE TITLE
Anchor links to internal pages

### ISSUE THREAD

**Issue by SachinPath** [bloomreach/docs-feedback#111]
https://xmdocumentation.bloomreach.com/library/end-user-manual/editing-a-document.html

This page does not explain if anchored links can be set-up using the internal link. there is a field on the document picker pop-up but detailed guidance is not available.

**Comment by nvankampenhout** [comment]
Thanks @SachinPath , we amended the documentation page with a short paragraph and screenshot explaining the options at the bottom of the link picker (Anchor, Title, Open in new window).
