### ISSUE TITLE
Possible syntax errors in the Freemarker example for the context aware lightbox with a missing double quote

### ISSUE THREAD

**Issue by jpierson-at-riis** [bloomreach/docs-feedback#113]
In the following example, the attribute setting of `hippohtml=document.html"` on the `hst.html` directive is missing a beginning double quote. I believe they have to be matching and should likely have been written as `hippohtml="document.html"`.

https://xmdocumentation.bloomreach.com/13/library/concepts/rewriting-rich-text-field-runtime/hst-2-example-of-context-aware-lightbox-for-all-inline-images.html

```freemarker
<@hst.defineObjects/>
<#if hstRequest.requestContext.attributes['wideview'] == true>
  <@hst.html hippohtml=document.html"
             contentRewriter="${lightboxContentRewriter}">
    <@hst.imagevariant name="mygallery:sixteencolumn"/>
  </@hst.html>
<#else>
  <@hst.html hippohtml=document.html"
             contentRewriter="${lightboxContentRewriter}">
    <@hst.imagevariant name="mygallery:ninecolumn"/>
  </@hst.html>
</#if>
```

**Comment by nvankampenhout** [comment]
Thanks @jpierson-at-riis ! I think these may be object references that should be written without any quotes but I'll have to verify.

**Comment by nvankampenhout** [comment]
Confirmed & fixed. Thanks!
