### ISSUE TITLE
Curl Example: Download Heap Dump

### ISSUE THREAD

**Issue by MPriess** [bloomreach/docs-feedback#115]
In the current example with curl the parameter -o is missing so that the heapdump can be saved to disk.

Could you please add -o heapdump.hprof:
```
curl -X GET \
  https://api.<stackname>.bloomreach.cloud/v3/environments/<env-id>/heapdump/oomcreated \
  -H 'Accept-Encoding: gzip' \
  -H 'Authorization: Bearer <auth-token>' \
  -H 'cache-control: no-cache' \
  -d '{
  "fileId": ""
}' \
-o heapdump.hprof
```

https://xmdocumentation.bloomreach.com/bloomreach-cloud/reference-documentation/monitor-and-analyze-jvm-memory.html

**Comment by nvankampenhout** [comment]
Good suggestion, done. Thanks @MPriess !
