### ISSUE TITLE
Essentializer plugin is outdated

### ISSUE THREAD

**Issue by ienemien** [bloomreach/docs-feedback#118]
https://xmdocumentation.bloomreach.com/library/essentials-plugins/archetype.html

You are referring to the Essentializer plugin here as an option to create your own Essentials Plugin, but this plugin itself hasn't been updated for a long time and is not working anymore, so probably best not to refer to it anymore.

**Comment by nvankampenhout** [comment]
Thanks @ienemien , you are absolutely right, the Essentializer Plugin is very outdated. I removed the reference to it from the documentation page.
