### ISSUE TITLE
several grammar mistakes.

### ISSUE THREAD

**Issue by joeyliechty** [bloomreach/docs-feedback#12]
https://documentation.bloomreach.com/library/concepts/crisp-api/examples/web-hook-example-to-invalidate-cache.html

![Screen Shot 2020-02-12 at 2 40 30 PM](https://user-images.githubusercontent.com/60985885/74375590-35c16c80-4da6-11ea-9769-c352aa3c30e1.png)

**Comment by nvankampenhout** [comment]
Thanks for your feedback. We'll mark the page for review.

**Comment by nvankampenhout** [comment]
Page reviewed and improved
