### ISSUE TITLE
Improve the page "monitor environment with newrelic"

### ISSUE THREAD

**Issue by MPriess** [bloomreach/docs-feedback#120]
I have no experience with New Relic yet, and so far only have a rough idea of what is possible with New Relic.

Would it be possible to make the documentation here a little more detailed. What metrics are available to me here? Everything what the JVM provides (Heap ...)? 

Some additional screenshots would be fine, to get a rough idea.

https://xmdocumentation.bloomreach.com/bloomreach-cloud/reference-documentation/monitor-environment-with-new-relic.html

**Comment by nvankampenhout** [comment]
Hi @MPriess , 

I accessed our New Relic test account and had a look around. There is a ton of things you can monitor including many (all?) JVM metrics. You can also monitor transactions and database connections among others, and track and triage any Java exceptions that may occur. I lack expertise in this area to really say anything more useful about it but if you have any specific questions about certain metrics being available, let me know and I'd be happy to find out for you.

I added some generic info and screenshots to the documentation page. We are working on getting the site to render higher resolution screenshots, stay tuned.

Thanks for your feedback!
Niels
