### ISSUE TITLE
Outdated Links in Docs

### ISSUE THREAD

**Issue by wendelb** [bloomreach/docs-feedback#125]
Hi! The page https://xmdocumentation.bloomreach.com/library/development/quick-wins.html contains outdated links in the following line:

"Optimize SEO value using the  [Sitemap](http://sitemap.forge.onehippo.org/), [SEO Support](https://forge.onehippo.org/gf/project/hst-seo-support/), and [Robots.txt](http://forge.onehippo.org/gf/project/robotstxt/) plugins."

All 3 of those links don't work anymore as the forge was moved in *2017*. Further, I only checked the robots.txt plugin which does not seem to exist anymore.

Can you please replace the links with current ones?

Thanks

**Comment by nvankampenhout** [comment]
Thanks @wendelb , I updated the links.
