### ISSUE TITLE
The word "diagram" is repeated unecessarily in the referenced sentence.

### ISSUE THREAD

**Issue by jpierson-at-riis** [bloomreach/docs-feedback#127]
The sentence "The diagram diagram therefore places the Userrole element in the crosshair between these 4 dimensions." includes the word diagram repeated once more than necessary.

https://xmdocumentation.bloomreach.com/library/concepts/security/authorization-model-concepts.html

**Comment by nvankampenhout** [comment]
Thanks @jpierson-at-riis for taking the time to report this. I removed the redundant "diagram".
