### ISSUE TITLE
link target is empty

### ISSUE THREAD

**Issue by erictheun** [bloomreach/docs-feedback#128]
https://xmdocumentation.bloomreach.com/library/concepts/plugins/taxonomy/migrate-to-the-taxonomy-field.html

`In the [Delivery API](https://xmdocumentation.bloomreach.com/homepage/delivery-api.html), a taxonomy field will show the field like in the example below, with a taxonomyValues entry as an taxonomyAllValues entry, meaning with ancestors:`

TheDelivery API link target is an empty page.

**Comment by nvankampenhout** [comment]
Thanks @erictheun , the link has been fixed.
