### ISSUE TITLE
Mistake in version

### ISSUE THREAD

**Issue by erictheun** [bloomreach/docs-feedback#130]
In the right column of the table, the target version is stated as 15.3.0-SNAPSHOT version. I'm guessing it should be 15.3.0 ;-)?

https://xmdocumentation.bloomreach.com/about/release-notes/15/15.3.0-detailed-release-notes.html

**Comment by nvankampenhout** [comment]
Thanks for spotting this one as well, @erictheun , we should hire you as editor! ;-)

Looks like this was generated before the release was tagged, the version number is now fixed.
