### ISSUE TITLE
Wrong override file name for Customize JSON Serialization of Domain-Specific POJO Models?

### ISSUE THREAD

**Issue by sebastianBoehringer** [bloomreach/docs-feedback#132]
https://xmdocumentation.bloomreach.com/library/concepts/page-model-api/customization.html
I am just assuming that the file for the custom beans should be site/components/src/main/resources/META-INF/hst-assembly/overrides/addon/org/hippoecm/hst/pagemodelapi/**v10**/ instead of site/components/src/main/resources/META-INF/hst-assembly/overrides/addon/org/hippoecm/hst/pagemodelapi/**v09**/ if you are using the delivery API in version 1.0

**Comment by nvankampenhout** [comment]
Thanks for the heads-up @sebastianBoehringer . Your assumption is correct. The documentation page has been updated.
