### ISSUE TITLE
Info about having to restart twice unclear

### ISSUE THREAD

**Issue by ienemien** [bloomreach/docs-feedback#133]
https://xmdocumentation.bloomreach.com/library/concepts/plugins/robots.txt/configuration.html

I don't see any message saying I have to restart after the first restart, the link to 'Plugin installation' is also missing.

**Comment by nvankampenhout** [comment]
Thanks for the heads-up, @ienemien . I confirmed the second rebuild & restart is no longer required and updated the documentation page.
