### ISSUE TITLE
Please add where the action-list is/are located 

### ISSUE THREAD

**Issue by TimoPot** [bloomreach/docs-feedback#134]
https://xmdocumentation.bloomreach.com/library/concepts/configuration-management/manage-content.html?_gl=1*ucgq4r*_ga*MTI5MTg0OTgxMi4xNjgzNTQ2NzU4*_ga_QNZ568TB7S*MTY5OTUxNjI0NC42Ni4xLjE2OTk1MTY1MDAuMzIuMC4w

**Comment by nvankampenhout** [comment]
I added an explicit reference to the typical location of the hcm-actions.yaml file to the "Content actions" section.

Hope this helps.
