### ISSUE TITLE
Generating API Documentation in Swagger Format is not working

### ISSUE THREAD

**Issue by x7Git** [bloomreach/docs-feedback#136]
https://xmdocumentation.bloomreach.com/library/concepts/rest/restful-api-support---plain-jax-rs-services.html

Hi guys,

the documentation for the Open API / Swagger does not work. I even tried it on a greenfield project with brXM version 15.5.0. Can you please update the documentation or remove it?

**Comment by nvankampenhout** [comment]
Thanks for the heads-up @x7Git , we'll look into it and follow up.

**Comment by nvankampenhout** [comment]
Hi @x7Git , we verified that the configuration to generate the Open API / Swagger specification still works as described in the documentation.

Make sure the "resourcePackage" property value matches the Java package your REST classes are in and that the classes have the relevant Swagger annotations added.

If it still doesn't work, I recommend you open a support ticket with Bloomreach, providing a reproduction path.

I hope this helps.
