### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by GeoffreyHayward** [bloomreach/docs-feedback#138]
https://xmdocumentation.bloomreach.com/11/library/concepts/plugins/taxonomy/about.html

The link for https://code.onehippo.org/cms-community/hippo-plugin-taxonomy does not work.

**Comment by nvankampenhout** [comment]
Hi @GeoffreyHayward , brXM 11 is EOL and the documentation is no longer maintained. For the most up to date version of that page, including an updated link to the source code, see https://xmdocumentation.bloomreach.com/library/concepts/plugins/taxonomy/about.html.

Hope this helps.
