### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by GeoffreyHayward** [bloomreach/docs-feedback#139]
https://xmdocumentation.bloomreach.com/13/library/concepts/plugins/taxonomy/category-detail-view-editor-customization.html

The link for the demo project does not work.

**Comment by nvankampenhout** [comment]
Hi @GeoffreyHayward , brXM 13 is EOL and its documentation is no longer maintained.

In the current brXM version, the Taxonomy demo can be installed as a plugin using the [Essentials](https://xmdocumentation.bloomreach.com/library/setup/using-the-setup-dashboard.html) app.

Hope this helps.
