### ISSUE TITLE
Content issues on XM Experience Pages Configuration

### ISSUE THREAD

**Issue by jvalteren** [bloomreach/docs-feedback#140]
See: https://xmdocumentation.bloomreach.com/library/concepts/experience-pages/configuration.html

The mixin `hippostd:cmxpagefolder` is not mentioned in the 'Experience Page Folder' paragraph under 'Required Configuration'.

Also, under the 'Experience Page Layouts' paragraph, the xpages node path seems to be incorrect (concatenated 2 node paths): `/hst:myproject/hst:configurations/myproject/hst:xpages/hst:myproject/hst:configurations/myproject/hst:xpages`

**Comment by nvankampenhout** [comment]
Hi @jvalteren ,
Thanks for your feedback! We updated the page to fix the issues you reported.
