### ISSUE TITLE
Conflict with the existing homepage

### ISSUE THREAD

**Issue by ivoeersels** [bloomreach/docs-feedback#17]
https://documentation.bloomreach.com/13/trails/deep-dive/hello-world.html

After creating a new project and building it, you already have a 'homepage' under 'hst:pages'. The tutorial doesn't mention it and the rest of it seems to conflict with it as the 'root' of 'hst:sitemap' is already taken by that homepage.

I worked around this myself by creating a hst:page node with name 'helloworld' and added a 'helloworld' node under 'hst:sitemap'. Also imitated the properties of the other sitemap nodes (hst:componentconfigurationid, hst:pagetitle,hst:refId).
Ended up being able to access my helloworld page via url 'http://localhost:8080/site/helloworld'.

I think it makes sense to incorporate this into the tutorial, either by instructing to delete all the nodes referencing the existing homepage from the archetype or by doing what I did and create a separate page.

**Comment by nvankampenhout** [comment]
Thanks for your feedback. If you follow the steps described on that page and use an empty archetype project, there should not be any pages configured yet under 'hst:pages'. It sounds like you added some features from the Essentials library, in which case indeed there are page configurations, sitemap items etc. added that conflict with the rest of the tutorial.

We could add some text that explicitly says not to add any features to the empty project.

**Comment by ivoeersels** [comment]
Yes, I assume that is exactly what happened. At the top of the page there is a link to the Essentials setup application. I may have added the Banners feature and this apparently automatically also adds

**Essentials Site Skeleton**
Provides a basic site structure for adding features, such as a basic sitemap, an empty menu and styling.

Changes made by this feature

 Create project file 'C:\gitprojects\myproject\repository-data\webfiles\src\main\resources\site\freemarker/myproject/homepage-main.ftl'.
...
 Import file 'instructions/content/homepage-labels.xml' to repository parent node '/content/documents/administration/labels'.
...
 Import file 'instructions/xml/hst/templates/homepage-main-freemarker.xml' to repository parent node '/hst:myproject/hst:configurations/myproject/hst:templates'.
...
 Import file 'instructions/xml/hst/workspace/homepage.xml' to repository parent node '/hst:myproject/hst:configurations/myproject/hst:workspace/hst:containers'.
...
 Import file 'instructions/xml/hst/pages/homepage.xml' to repository parent node '/hst:myproject/hst:configurations/myproject/hst:pages'.
...

So yes, maybe it is a good idea to explicitly mention not to add any features for the Hello World trail.
