### ISSUE TITLE
Maybe it could be a good idea to rename the headContributions HST tag?

### ISSUE THREAD

**Issue by ivoeersels** [bloomreach/docs-feedback#18]
https://documentation.bloomreach.com/13/trails/developer-trail/configure-out-of-the-box-features/configure-home-page.html

It feels weird to have a tag called 'headContributions which has categories which can indicate to NOT add it to the html <head> after all? Maybe you could call it 'hst.clientLib' instead? I also work with Adobe Experience Manager, so to me that feels like a more logical name for a tag which contains CSS and/or JS.

If you opt for something like this, I guess it would be a good idea to support both for a while but only use the new name in tutorials and remove the old one after a while.

**Comment by nvankampenhout** [comment]
The developer community (https://community.bloomreach.com/c/developers) is a better place for this kind of feedback, many Bloomreach engineers actively participate in discussions there.

Over here we only deal with documentation :)
