### ISSUE TITLE
Location of configuration of the maven-war-plugin

### ISSUE THREAD

**Issue by jenskooij** [bloomreach/docs-feedback#2]
It says in the documentation the configuration of the maven-war-plugin resides in cms/pom.xml, but I found it's location to be in the root pom.xml
https://documentation.bloomreach.com/library/upgrade-12-to-13/steps/miscellaneous-upgrade-steps.html

**Comment by nvankampenhout** [comment]
Thanks for your feedback! We'll look into this ASAP and report back here.

**Comment by nvankampenhout** [comment]
Hi Jens,

I had a look and AFAICS, the location really should be cms/pom.xml. You can verify this by generating a project using the v12 archetype (https://documentation.bloomreach.com/12/trails/getting-started/hippo-essentials-getting-started.html).

Maybe the project you are upgrading was customized or previously upgraded from a pre-v12 release?

Thanks,
Niels

**Comment by jenskooij** [comment]
Well yes, the project had been upgraded all the way from 7.7 through 13. Does that explain the alternative location of this maven-war-plugin though? 😋

**Comment by nvankampenhout** [comment]
With such an impressive upgrade sequence I'd say that's very likely! :)

Unfortunately, it's not feasible for us to account for all possible project configurations out there in the real world so we take the previous major release of the archetype as a baseline for the upgrade docs.

Anyway, don't let this discourage you from providing feedback like this, it is much appreciated.
