### ISSUE TITLE
i18n - missing paths

### ISSUE THREAD

**Issue by ZigaVukcevicDev** [bloomreach/docs-feedback#20]
https://documentation.bloomreach.com/14/library/concepts/translations/hst-2-i18n-support.html

I don't see full path stated for file:

a) `web.xml`
b) `messages_en_US.properties` (there is just `src/main/resources` mentioned) 

This makes a confusion as project:

a) has multiple files named __web.xml__
b) has multiple folders named __src/main/resources__

**Comment by nvankampenhout** [comment]
Thanks for your feedback, I marked that page for review. We will pick this up soon.

**Comment by nvankampenhout** [comment]
I had a quick look and made some improvements, I think it should be more clear now.

**Comment by ZigaVukcevicDev** [comment]
@nvankampenhout thanks for the update.
