### ISSUE TITLE
Problem with the 'localhost' hostname in HTTPS

### ISSUE THREAD

**Issue by ivoeersels** [bloomreach/docs-feedback#21]
https://documentation.bloomreach.com/13/library/development/configure-cargo-for-https-ssl-tls.html

After strictly following the documentation instructions both these URLs result in the same error:
https://localhost:8443/cms/console/
https://localhost:8443/cms/

> Bad Request
> This combination of host and port requires TLS.

If I change the hostname to 127.0.0.1 they work however?

If I look at my browser dev tools it seems like https://localhost:8443/cms/console/ gets 301 redirected to http://localhost:8443/cms/console/ for some reason

**Comment by nvankampenhout** [comment]
Hi, thanks for your feedback. Marking this page for review.

**Comment by nvankampenhout** [comment]
This page has now been updated. The missing part was that since v13 the HST host configuration also needs to be updated for the platform.

Thanks again for your feedback!
