### ISSUE TITLE
UI of website is very annoying

### ISSUE THREAD

**Issue by RahulTapadiya** [bloomreach/docs-feedback#22]
https://documentation.bloomreach.com/14/library/concepts/plugins/create-a-custom-field-validator.html

UI of website is very annoying,
Please create better UI.
Index on the right side of the page makes reading documentation very bad experience.
It doesn't let us read/copy documentation properly and sometime hides the content of the page.
Either provide a button to collapse the index OR remove index on the right side of the page as it serves very little purpose.

I am using latest Chrome on MAC.

<img width="1431" alt="Screen Shot 2020-04-15 at 6 38 51 PM" src="https://user-images.githubusercontent.com/11985890/79395872-9c9b0780-7f48-11ea-86aa-554d5e105bad.png">

**Comment by niklaswinkels** [comment]
Hi @RahulTapadiya  - Thanks for your feedback! Love the idea of collapsing the sidebar. I've heard this a few times now, that the space for the content might be a little too small. I'll make sure we'll include your suggestion in the next UI update 👍

**Comment by RahulTapadiya** [comment]
Great, many Thanks @niklaswinkels

**Comment by aredridel** [comment]
Seconding this! it makes the most technical documentation almost unreadable.
