### ISSUE TITLE
Docker tutorial still impacted by known issue of docker-maven-plugin

### ISSUE THREAD

**Issue by ivoeersels** [bloomreach/docs-feedback#23]
https://documentation.bloomreach.com/13/library/development/docker/run-and-develop-with-docker.html

When following the tutorial the mvn -Pdocker.build fails with error 'Connection is still allocated'.
https://github.com/fabric8io/docker-maven-plugin/issues/1152

Could you please upgrade your dependency in hippo-cms7-release-13.4.0.pom (and above if also impacted)
from
<docker.maven.plugin.version>0.28.0</docker.maven.plugin.version>

to
<docker.maven.plugin.version>0.30.0</docker.maven.plugin.version>
or above.

I got it working by putting <docker.maven.plugin.version>0.30.0</docker.maven.plugin.version> in my local project root POM, but it is quite frustrating if you follow a documentation that the first set of commands already fails.

**Comment by nvankampenhout** [comment]
Thanks, I'll ask the engineering team to update the dependency in the next release.

**Comment by nvankampenhout** [comment]
Looks like this issue has been on our radar for a while but hasn't had priority:
https://issues.onehippo.com/browse/CMS-12060
We'll try to fix it in the next release, in the meantime I'll add a note to the documentation page to override the docker plugin version in the local project pom.

**Comment by nvankampenhout** [comment]
I added a note to https://documentation.bloomreach.com/14/library/development/docker/run-and-develop-with-docker.html and https://documentation.bloomreach.com/13/library/development/docker/run-and-develop-with-docker.html.
