### ISSUE TITLE
confused on what 'the web design' is

### ISSUE THREAD

**Issue by kieranld** [bloomreach/docs-feedback#25]
https://documentation.bloomreach.com/14/trails/developer-trail/configure-out-of-the-box-features/add-static-resources.html

In this page it says "In the folder structure of the web design these resources are located in the following folders:" and redirects the user back to "(see Introduction for up-to-date download link)" to find the files, but on the Introduction page there is no clear indication of where these files are located. I assume what's supposed to be happening here is we're copying static resources into this directory so they're available to our app? But where are these files we're supposed to add?

**Comment by nvankampenhout** [comment]
Hi,

On https://documentation.bloomreach.com/14/trails/developer-trail/introduction.html, under 'Approach', see the first bullet item 'Download the GoGreen web design from Github' which links to  https://github.com/bloomreach/website-tutorial/tree/web-design.

I agree it might not be very clear so we'll put this on the todo list to improve.

Hope this helps. Thanks for your feedback!

**Comment by kieranld** [comment]
@nvankampenhout Thank you for clarification. I did eventually figure it out, but I started with a blank archetype so it wasn't clear where the files were until I downloaded the finished project and looked around.
