### ISSUE TITLE
error

### ISSUE THREAD

**Issue by realjax** [bloomreach/docs-feedback#3]
https://documentation.bloomreach.com/trails/getting-started/creating-a-project.html

very first command throws error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:generate (default-cli) on project standalone-pom: The desired archetype does not exist (org.onehippo.cms7:hippo-project-archetype:13.4.)

**Comment by nvankampenhout** [comment]
It looks like you are missing a '0' at the end of the version number ('13.4.' i.s.o. '13.4.0').

**Comment by realjax** [comment]
Thanks. Turned out the problem was caused by the fact I needed to add an additional server entry in my settings.xml

**Comment by nvankampenhout** [comment]
Hmm, that shouldn't be necessary because of the -DarchetypeRepository=https://maven.onehippo.com/maven2 argument in the Maven command.

**Comment by realjax** [comment]
Ok but still.. the solution here https://community.bloomreach.com/t/cant-create-project-from-archetype-for-version-13-0-0/719 is what solved it for me as well 😀

**Comment by nvankampenhout** [comment]
That community thread was about a version that was not publicly released yet at that time. 13.4.0 is publicly available from https://maven.onehippo.com/maven2/org/onehippo/cms7/hippo-project-archetype/13.4.0/ so that's why it's strange you got that error. I'm glad to hear you got it working but on our end we need to look into this ;-)

**Comment by realjax** [comment]
I was thinking... Maybe your initial reply was my true problem. (The left out 0). Maybe I changed the settings.xml and tried again with the correct command which then succeeded but not because of the additional server entry!  😀 I'm afraid I can't rule out that scenario. Anyway, thanks for your help, appreciated!
