### ISSUE TITLE
Missing version

### ISSUE THREAD

**Issue by GeoffreyHayward** [bloomreach/docs-feedback#30]
Re: https://documentation.bloomreach.com/14/trails/getting-started/creating-a-project.html

The following error message is given by Maven:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:generate (default-cli) on project standalone-pom: The desired archetype does not exist (org.onehippo.cms7:hippo-project-archetype:14.2.1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

**Comment by nvankampenhout** [comment]
Apologies, 14.1.0 is the latest publicly available version. This is now fixed on the page. 

14.2.1 has been released to our enterprise customers and will become publicly available in ~6 weeks.

Thanks for your feedback!
