### ISSUE TITLE
broken link in customer facing docs

### ISSUE THREAD

**Issue by joeyliechty** [bloomreach/docs-feedback#37]
https://documentation.bloomreach.com/14/library/concepts/document-types/how-to-structure-your-data--content.html

link goes to pagenotfound
![Screen Shot 2020-06-22 at 1 12 48 PM](https://user-images.githubusercontent.com/60985885/85321336-2b1c8f80-b48a-11ea-9c17-8b21e9770106.png)

**Comment by nvankampenhout** [comment]
Thanks, seems like the linked blog post doesn't exist anymore so I removed the link.

**Comment by joeyliechty** [comment]
Oh... I was hoping to read that content 😟

**Comment by nvankampenhout** [comment]
It looked like that link had been there since at least Hippo CMS 10 so the blog post it pointed to was probably outdated. I suspect it didn't survive the move from the old Hippo blog to https://developers.bloomreach.com/blog.
