### ISSUE TITLE
Source Code Missing?

### ISSUE THREAD

**Issue by niklaswinkels** [bloomreach/docs-feedback#4]
https://documentation.bloomreach.com/library/concepts/plugins/taxonomy/about.html

I believe the link to the source code is outdated?

**Comment by nvankampenhout** [comment]
The link to the source code is correct but some of the pages were outdated. Most are now up to date, one has been removed. The source code for 14.0 is not public yet as it has just been released last week so we are ~5-6 weeks from public disclosure.
