### ISSUE TITLE
Update to proper userrole

### ISSUE THREAD

**Issue by nicholaslyon-dt** [bloomreach/docs-feedback#40]
https://documentation.bloomreach.com/14/library/enterprise/enterprise-features/content-reports/add-content-reports-to-project.html

The documentation says the userrole to access Content Reports is xm.reports.user. This is wrong, there is no s. It's xm.report.user.

![Screen Shot 2020-07-02 at 3 13 44 PM](https://user-images.githubusercontent.com/41478918/86400480-ae05cd00-bc76-11ea-95a5-af26746ce197.png)

**Comment by nvankampenhout** [comment]
You are right, thanks for spotting that. I updated the page.

Looks like this was the only page that had this mistake, all other relevant pages I could find correctly have 'xm.report.user'.

Thanks for your feedback!
