### ISSUE TITLE
Maven dependency information missing

### ISSUE THREAD

**Issue by GeoffreyHayward** [bloomreach/docs-feedback#41]
https://documentation.bloomreach.com/14/library/concepts/crisp-api/unit-testing.html The maven dependency for org.onehippo.cms7.crisp.mock.module.MockCrispHstServices is not given.

**Comment by nvankampenhout** [comment]
Thanks for your feedback! From a quick search one [maven.onehippo.com](https://maven.onehippo.com/#nexus-search;quick~crisp), you'd probably need hippo-addon-crisp-mock. I'll confirm with the relevant development team and schedule some time to update the page.

**Comment by nvankampenhout** [comment]
The page has been updated to include the required Maven dependency.
