### ISSUE TITLE
another reason for "Channel toolbar is not initialized"

### ISSUE THREAD

**Issue by joeyliechty** [bloomreach/docs-feedback#49]
https://documentation.bloomreach.com/14/library/concepts/spa-integration/troubleshooting.html
This page is missing an additional reason why the toolbar is not initialized
This can also happen if you're loading components asynchronously and you don't call the .sync() function after the page has loaded.
https://www.npmjs.com/package/@bloomreach/spa-sdk#page

**Comment by nvankampenhout** [comment]
Added to https://documentation.bloomreach.com/14/library/concepts/spa-integration/troubleshooting.html under "Channel toolbar is not initialized".
