### ISSUE TITLE
Use real class

### ISSUE THREAD

**Issue by epegar** [bloomreach/docs-feedback#5]
https://documentation.bloomreach.com/12/library/concepts/error-pages-and-error-handling/2.-add-a-catch-all-sitemap-item-that-creates-a-dynamic-404-page.html

Use EssentialsPageNotFoundComponent instead of org.hippoecm.hst.demo.components.Set404Component

**Comment by nvankampenhout** [comment]
Thanks for your feedback. This pages has now been updated for brXM v14:

https://documentation.bloomreach.com/library/concepts/error-pages-and-error-handling/2.-add-a-catch-all-sitemap-item-that-creates-a-dynamic-404-page.html
