### ISSUE TITLE
misleading config

### ISSUE THREAD

**Issue by yeahdef** [bloomreach/docs-feedback#54]
https://documentation.bloomreach.com/14/library/concepts/page-model-api/configuration.html#

on this page, the hst configuration is
/hst:hst/hst:hosts/dev-localhost/localhost/hst:root/myapp:
  jcr:primaryType: hst:mount
  hst:mountpoint: /hst:hst/hst:sites/myapp
  hst:namedpipeline: SpaSitePipeline
  hst:pagemodelapi: resourceapi

however, in a default archetype with the project named "myapp"
the hst:mountpoint would be /hst:myapp/hst:sites/myapp

**Comment by nvankampenhout** [comment]
You are right. I changed it into /hst:myproject which is the default archetype value. This was actually already used in the other JCR snippet lower down on the same page.

Thanks!
