### ISSUE TITLE
Where are the test suits? Repo is empty.

### ISSUE THREAD

**Issue by meehaws** [bloomreach/docs-feedback#56]
https://documentation.bloomreach.com/14/library/development/hippo-test-suite.html

**Comment by nvankampenhout** [comment]
Hi @meehaws,

Thanks for the heads-up, the code for the latest public brXM releases, including the test suite, can now be found at GitHub:

https://github.com/bloomreach/brxm.git

You'll have to clone the entire brxm repository and checkout the latest tag (brxm-14.3.3 at this moment). The Test Suite is in the testsuite directory.

I'll update the documentation page ASAP.

Thanks!

**Comment by nvankampenhout** [comment]
https://documentation.bloomreach.com/14/library/development/hippo-test-suite.html is now updated.
