### ISSUE TITLE
Maven build scripts fail with version 14.3.3

### ISSUE THREAD

**Issue by nrs107** [bloomreach/docs-feedback#57]
https://documentation.bloomreach.com/14/trails/getting-started/building-a-project.html

The Maven build scripts fail for version 14.3.3 -- there's a missing dependency.

They work correctly with version 14.2.2

**Comment by nvankampenhout** [comment]
Thanks @nrs107 , we'll look into it asap.

**Comment by nvankampenhout** [comment]
Confirmed, created product issue https://issues.onehippo.com/browse/CMS-14217

@nrs107 , as a temporary workaround, you can override that property in the project root pom.xml. Look for the properties section, where it says:

    
    

Add in the property like this:

    
    <hippo.maven.plugin.l10n>14.3.3</hippo.maven.plugin.l10n>
    

With this workaround the project should build successfully.

**Comment by nvankampenhout** [comment]
The missing artifact has been published to the public Maven repository so this issue should now be resolved.
