### ISSUE TITLE
Archetype Version 14.0.0-2 is missing

### ISSUE THREAD

**Issue by GeoffreyHayward** [bloomreach/docs-feedback#6]
On the page https://documentation.bloomreach.com/trails/getting-started/creating-a-project.html -DarchetypeVersion=14.0.0-2 is given, however https://maven.onehippo.com/maven2/org/onehippo/cms7/hippo-project-archetype/ stops at 14.0.0-1/.

**Comment by GeoffreyHayward** [comment]
Also, to get 14.0.0-1 running I had to add the following to the root POM.

```xml
<pluginRepositories>
  <pluginRepository>
    <id>hippo</id>
    <name>Hippo maven 2 repository.</name>
    <url>https://maven.onehippo.com/maven2/</url>
  </pluginRepository>
</pluginRepositories>
```
Otherwise the plugin `org.onehippo.cms.l10n:hippo-cms-l10n-maven-plugin:14.0.0` could not be found.

**Comment by nvankampenhout** [comment]
Thanks, we'll look into this asap!

**Comment by ajbanck** [comment]
archetype 14.0.0-2 has been (re)deployed and should now be accessible.
I verified with 14.0.0-2 that the l10n plugin is defined in the parent project-pom and a project works without adding the pluginRepository. Please let us know if you still have an issue with the 14.0.0-2 release

**Comment by GeoffreyHayward** [comment]
Many thanks, I can confirm it's working on 14.0.0-2 without a `pluginRepository` now.
