### ISSUE TITLE
Duplicating hst:xpages layouts

### ISSUE THREAD

**Issue by arthurk777** [bloomreach/docs-feedback#60]
Hi, on the bottom of this page:

https://documentation.bloomreach.com/14/library/concepts/hst-configuration-model/experience-page-layouts-configuration.html

"Note that this means that whenever a different channel needs the same hst:xpages layouts, you need to duplicate them."

I'm assuming it's okay to use a "common" configuration that has hst:xpages and channel specific configurations can hst:inheritsfrom?

Thanks!

**Comment by nvankampenhout** [comment]
Yes, that should work. I'll confirm and update the page. Thanks!

**Comment by nvankampenhout** [comment]
Hi, I verified this and updated the page. Thanks again for your feedback!
