### ISSUE TITLE
Experience Pages code examples?

### ISSUE THREAD

**Issue by arthurk777** [bloomreach/docs-feedback#61]
Nice work on adding the Experience Pages feature.

I was trying to understand how to best roll-out this feature in an existing implementation.  I think it would help to provide code examples.

https://documentation.bloomreach.com/14/library/concepts/experience-pages/tutorial.html

For example, our existing custom components rely on external content documents to work, using ParametersInfo with "pickerConfiguration = "cms-pickers/documents-only".

In the new Experience Pages setup, I could see the document type containing all the fields needed to be entirely self-contained (we can publish one document instead of the Xpage + external document).  The component code could then retrieve the document data using request.getRequestContext().getContentBean() instead of getDocument().  Is this the recommended approach? 🤷‍♂️

**Comment by nvankampenhout** [comment]
Hi, thanks for your feedback. For questions regarding your specific implementation it is best to go through the support portal (https://support.bloomreach.com/) or our community forum (https://community.bloomreach.com/). Thanks.
