### ISSUE TITLE
why the login???

### ISSUE THREAD

**Issue by realjax** [bloomreach/docs-feedback#65]
https://documentation.bloomreach.com/14/library/enterprise/enterprise-features/two-factor-authentication/two-factor-authentication-with-duo-security.html

Why is a login needed???

**Comment by nvankampenhout** [comment]
Hi, some of our documentation pages are only available to our customers and partners. If you are or work for a Bloomreach customer or partner you can request an account at https://documentation.bloomreach.com/signup

I'm checking internally whether the login for this particular page still makes sense.

**Comment by nvankampenhout** [comment]
Hi, after an internal review we removed the login from that page. Please note that the described feature still requires an enterprise license.

**Comment by realjax** [comment]
Hi,

thanks for the response!

regards,
Jacco Huysmans
