### ISSUE TITLE
Wrong @Override method name for Channel Filters

### ISSUE THREAD

**Issue by stifm** [bloomreach/docs-feedback#67]
https://documentation.bloomreach.com/13/library/upgrade-12-to-13/steps/upgrade-hst-code.html

The upgrade documentation - as well as the linked [Channel Filtering](https://documentation.bloomreach.com/13/library/concepts/channels/channel-filtering.html) page - repeatedly mentions and shows code snippets with an `#apply` method.
While this was the case with `com.google.common.base.Predicate`, it doesn't apply to `java.util.function.BiPredicate`, where `#test` has to be used instead. See `org.hippoecm.hst.platform.services.channel.ContentBasedChannelFilter` for reference.

Tested with Java 8 and brXM 13.0.2 (as of yet).

**Comment by nvankampenhout** [comment]
Thanks for your feedback, @stifm. We'll verify and update these pages asap.

**Comment by nvankampenhout** [comment]
The following pages have been updated:

- https://documentation.bloomreach.com/13/library/upgrade-12-to-13/steps/upgrade-hst-code.html
- https://documentation.bloomreach.com/13/library/concepts/channels/channel-filtering.html
- https://documentation.bloomreach.com/14/library/concepts/channels/channel-filtering.html
