### ISSUE TITLE
Add manual steps for all Essentials Plugins

### ISSUE THREAD

**Issue by stifm** [bloomreach/docs-feedback#69]
https://documentation.bloomreach.com/13/library/enterprise/enterprise-features/url-rewriter/installation.html

The `Essentials' initial Project setup screen` sounds nice, doesn't help people in the middle of an upgrade, though.
For such cases sentences like `The necessary library dependencies are added to the cms and site modules` are unfortunately not sufficient.

Concrete problem at hand:
My local Cargo does not start up with the following error:
`[INFO] [talledLocalContainer] 2021-08-05 16:42:01,227 ERROR [RepositoryServlet.init:246] Error while setting up JCR repository:
[INFO] [talledLocalContainer] javax.jcr.RepositoryException: unchecked exception: org.onehippo.cm.model.impl.exceptions.MissingDependencyException: Project 'hippo-addon-urlrewriter' has a missing dependency 'hippo-plugin-selections'`

This is after upgrading brXM 12 to 13. During the 11 to 12 upgrade, we converted the Forge plugin to the Bloomreach managed plugin.
This was achieved by adding `hippo-addon-urlrewriter-module-hst` to the site module and `hippo-addon-urlrewriter-module-repository` as well as `hippo-addon-urlrewriter-module-cms` to the cms module.
This seems to not be enough anymore, but the Upgrade Documentation does not mention anything for this plugin.
I tried adding different `hippo-plugin-selections` dependencies as mentioned by the error message, which didn't work.

Currently only reverting the plugin back to the Forge variant prevents these Exceptions, but I'd like to keep using the Bloomreach variant of it.

**Comment by stifm** [comment]
I created a case to get help on the concrete problem, so this issue can focus on the suggestion to improve the documentation for Enterprise Plugins.
Alternatively, the upgrade documentation should include all necessary steps.

**Comment by nvankampenhout** [comment]
Thanks for your feedback @stifm. I suppose in scenarios like the one you describe it would be useful to explicitly list the required dependencies in the documentation.

Since you created a support case I suggest we let that play out first. If you could update here with the result, that would be great and then I'd be happy to update the documentation based on that.

**Comment by stifm** [comment]
The issue was resolved, the missing dependency was `hippo-plugin-selections-addon-repository`in the CMS pom.xml.

**Comment by nvankampenhout** [comment]
Thanks for the follow-up. I created a ticket in our internal issue tracking to make improvements to our documentation according to your suggestion.

Thanks again for your feedback!
