### ISSUE TITLE
Links point to onehippo.org

### ISSUE THREAD

**Issue by MPriess** [bloomreach/docs-feedback#71]
If you're looking for more information on how to get your special feature into your Bloomreach Experience Manager project, check out our **technical documentation** or our **community**. Follow the Build a Website tutorial to build a complete web site using Essentials' features.

https://documentation.bloomreach.com/14/trails/getting-started/configuring-a-project.html

**Comment by nvankampenhout** [comment]
Thanks, I updated the links!
