### ISSUE TITLE
Incorrect usernames used in yaml snippet

### ISSUE THREAD

**Issue by brayan-chinchilla** [bloomreach/docs-feedback#72]
The test users are configured to be:
- author-french
- editor-french

Later on, when users are added to their corresponding groups they are referenced as:
- french-author (non-existing)
- french-editor (non-existing)

![group_config_snippet](https://user-images.githubusercontent.com/9522100/130528787-7d2dff03-3180-4cb6-8198-14bab7cb8a79.png)

https://documentation.bloomreach.com/14/library/concepts/security/authorization-use-cases/grant-access-to-one-channel.html

**Comment by nvankampenhout** [comment]
Thanks @brayan-chinchilla, nice catch! I fixed the YAML snippets in the "Create Test Users" section, everything now consistently refers to french-author / french-editor.
