### ISSUE TITLE
Wrong JCR path "regex.pattern"

### ISSUE THREAD

**Issue by stifm** [bloomreach/docs-feedback#74]
https://documentation.bloomreach.com/13/library/concepts/plugins/create-a-custom-field-validator.html

The validator field `regex.pattern` was used in the old service and creates a `javax.jcr.PathNotFoundException: regexp.pattern` when using `hipposys:className: org.onehippo.cms.services.validation.validator.RegExpValidator`.

Thus it needs to be changed to `regexp.pattern`.

**Comment by nvankampenhout** [comment]
Hi, thanks for spotting and reporting this. This has now been fixed in https://documentation.bloomreach.com/13/library/concepts/plugins/create-a-custom-field-validator.html and https://documentation.bloomreach.com/14/library/concepts/plugins/create-a-custom-field-validator.html.
