### ISSUE TITLE
Deprecated? Provide SSL Certificate

### ISSUE THREAD

**Issue by MPriess** [bloomreach/docs-feedback#75]
https://documentation.bloomreach.com/14/bloomreach-cloud/reference-documentation/provide-ssl-certificate.html

This article is marked as deprecated. From my point of view this article is still relevant if you like to provide your own cert.

Article is referenced from:
https://documentation.bloomreach.com/14/bloomreach-cloud/reference-documentation/configure-dns-and-cdn.html
https://documentation.bloomreach.com/14/bloomreach-cloud/reference-documentation/configure-domains.html

**Comment by MPriess** [comment]
Article is referenced from

https://documentation.bloomreach.com/14/bloomreach-cloud/reference-documentation/configure-dns-and-cdn.html
https://documentation.bloomreach.com/14/bloomreach-cloud/reference-documentation/configure-domains.html

**Comment by nvankampenhout** [comment]
Hi, thanks for your feedback. I checked with the BRC team and indeed providing your own certificates is still supported although optional with the new bloomreach.cloud domain. I created an internal ticket to review and update the page.

**Comment by nvankampenhout** [comment]
Hi, the [page](https://documentation.bloomreach.com/14/bloomreach-cloud/reference-documentation/provide-ssl-certificate.html) has been updated and providing your own SSL certificate is now indicated as optional. Once again, thanks for your feedback.
