### ISSUE TITLE
Duplicated link

### ISSUE THREAD

**Issue by MPriess** [bloomreach/docs-feedback#76]
The words **Provide** and **SSL** are separate links which point to the same page. I would recommend to create one link **Provide SSL**.

https://documentation.bloomreach.com/14/bloomreach-cloud/reference-documentation/configure-domains.html

**Occurrence:**
Attachments: If preferred certificate management is a private cert, please follow the guide: **Provide** **SSL** certificate and attach the encrypted certs to the support case. 

When adding your own domain, Bloomreach Cloud will provide an option to manage your SSL certificates through DigiCert certificate authority. Please note that you will be required to add TXT validation record in your domain registrar in order to prove domain ownership.  You can however provide your own certificate if you wish to do that by raising a support request. For instructions on how to share your certificate please follow the guide: **Provide** **SSL certificate.**

**Comment by nvankampenhout** [comment]
Thanks for your feedback. The links have been fixed.
