### ISSUE TITLE
Is this API documentation?

### ISSUE THREAD

**Issue by aredridel** [bloomreach/docs-feedback#77]
https://documentation.bloomreach.com/api-reference/seo/widget-api/widget-api.html

This says it's API documentation but I'm finding no documentation of the actual calls.

**Comment by brpliao** [comment]
Hi Aria,

There is an example call on this page: https://documentation.bloomreach.com/api-reference/seo/widget-api/build-a-related-categories-related-items-and-related-products-widget.html

Information about the parameters are on this page: https://documentation.bloomreach.com/api-reference/seo/widget-api/parameters-for-the-widget-api.html

**Comment by aredridel** [comment]
Alright. It's confusingly laid out. I think that's sufficient, thank you.
