### ISSUE TITLE
Link point to a CDN

### ISSUE THREAD

**Issue by MPriess** [bloomreach/docs-feedback#79]
The link to the Paul Tuckey's Url Rewrite Filter point to a CDN, which display the HTML as RAW content.

I would recommend to set the link to the official page: https://tuckey.org/urlrewrite/

https://documentation.bloomreach.com/14/library/enterprise/enterprise-features/url-rewriter/use-the-url-rewriter.html

**Comment by nvankampenhout** [comment]
I fixed the link as suggested. Thanks for your feedback!
