### ISSUE TITLE
Links to JavaDoc Version 14.7 are broken

### ISSUE THREAD

**Issue by MPriess** [bloomreach/docs-feedback#81]
Seems like all links to version 14.7 throw an 404 error: 

https://documentation.bloomreach.com/14/library/about/javadoc.html

**Comment by nvankampenhout** [comment]
Thanks for the heads-up @MPriess ! Looks like something went wrong, we'll look into it asap.

**Comment by nvankampenhout** [comment]
The Javadoc links have been fixed. Thanks again for reporting this issue!
