### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by MPriess** [bloomreach/docs-feedback#82]
The link which point to OWASP (secure flag) is broken:

If, for security reasons, you want the _visitor cookie to have the **secure flag**, you can achieve this by configuring:

https://documentation.bloomreach.com/14/library/enterprise/enterprise-features/targeting/visitors-visits-and-cookies.html

**Comment by nvankampenhout** [comment]
Thanks @MPriess , the link has been fixed now.
