### ISSUE TITLE
Example does not work for me

### ISSUE THREAD

**Issue by mgilgar** [bloomreach/docs-feedback#84]
https://documentation.bloomreach.com/14/library/concepts/editor-interface/cms-perspectives.html

I have created a custom perspective as describe in the example but when I load it from the CMS I get a

Something went wrong (code 500)

And there is nothing in the logs or javascript console or javascript network tab in the browser.
I don't get anything clear when I debug.

I am using BR 14.7.3

**Comment by nvankampenhout** [comment]
Hi @mgilgar,

I created a quick test project from a 14.7.3 archetype and the custom perspective is working fine for me. I pushed my test project to a github repo for your reference:

https://github.com/nvankampenhout/docs-feedback-84

You can see the commits to add the customer perspective here:

https://github.com/nvankampenhout/docs-feedback-84/commit/7e13210281df8c730c2fd798e4e53992679a4fa5

I also added two screenshots to the project root.

I hope this helps. If you have any further questions, I suggest posting in the Bloomreach developer community forum:

https://community.bloomreach.com/
