### ISSUE TITLE
Possible mistake in package or class name in document

### ISSUE THREAD

**Issue by jpierson-at-riis** [bloomreach/docs-feedback#86]
https://documentation.bloomreach.com/12/library/upgrade-minor-versions/upgrade-12.6.10-to-12.6.11.html

Under the section labeled *(Relevance) Upgrade to Elasticsearch 7* the same class name is mentioned twice in the sentence when describing what to change something from and to.

> In your configuration for the visits data store, change the value of the targeting:storefactoryclass from `com.onehippo.cms7.targeting.storage.elastic7.ElasticStoreFactory` to `com.onehippo.cms7.targeting.storage.elastic7.ElasticStoreFactory`:

**Comment by jpierson-at-riis** [comment]
The same mistake seems to also exist here too.

https://documentation.bloomreach.com/13/library/upgrade-minor-versions/upgrade-13.4.3-to-13.4.4.html

**Comment by nvankampenhout** [comment]
Thanks @jpierson-at-riis , good catch. This should have been "from `com.onehippo.cms7.targeting.storage.elastic6.ElasticStoreFactory`" as documented at https://documentation.bloomreach.com/14/library/upgrade-minor-versions/upgrade-14.2-to-14.3.html.

I fixed it in https://documentation.bloomreach.com/12/library/upgrade-minor-versions/upgrade-12.6.10-to-12.6.11.html and https://documentation.bloomreach.com/13/library/upgrade-minor-versions/upgrade-13.4.3-to-13.4.4.html.

**Comment by jpierson-at-riis** [comment]
Awesome, thanks for the lightning fast change!
