### ISSUE TITLE
Link to JManage is broken

### ISSUE THREAD

**Issue by MPriess** [bloomreach/docs-feedback#88]
https://documentation.bloomreach.com/14/library/concepts/web-application/jmx-management-beans-support.html

The link to the JManage page is broken.

**Comment by nvankampenhout** [comment]
Thanks for the heads-up. It appears that the JManage website (http://www.jmanage.org) no longer exists. Let me check if there is any alternative we can link to. If not we'll remove the link.

**Comment by nvankampenhout** [comment]
Removed the broken link to JManage and added a link to JConsole.
