### ISSUE TITLE
Use of deprecated HippoItem.getProperty method in documentation

### ISSUE THREAD

**Issue by jpierson-at-riis** [bloomreach/docs-feedback#89]
The following two pages have more than one example each which makes use of the deprecated `getProperty` method on the `HippoItem` class.

https://documentation.bloomreach.com/14/library/concepts/content-beans/creating-content-beans.html
https://documentation.bloomreach.com/13/library/concepts/content-beans/creating-content-beans.html

According to the documentation it is recommended instead to use `getSingleProperty`.

> Deprecated
> Since 13.3.0. Use either getSingleProperty(String) for single fields or getMultipleProperty(String) for multiple fields.

These documentation pages should be updated so that all examples reflect the recommended method use.

**Comment by nvankampenhout** [comment]
Thanks for the heads-up, `getProperty` has now been replaced with `getSingleProperty` in the examples.
