### ISSUE TITLE
Humio Alerts link is dead

### ISSUE THREAD

**Issue by Moduo** [bloomreach/docs-feedback#90]
https://documentation.bloomreach.com/14/bloomreach-cloud/reference-documentation/monitor-and-analyze-jvm-memory.html

You're referring to a Humio Alerts page in the documentation but the link is dead. I suppose you wanted to link to: https://library.humio.com/stable/docs/automated/alerts/.

**Comment by nvankampenhout** [comment]
Thanks for the heads-up, the link has been updated.
