### ISSUE TITLE
Broken link to hippo-plugin-sitemap

### ISSUE THREAD

**Issue by jpierson-at-riis** [bloomreach/docs-feedback#91]
https://documentation.bloomreach.com/13/library/concepts/plugins/sitemap/about.html

The link to `https://code.onehippo.org/cms-community/hippo-plugin-sitemap` on this page appears broken.

![image](https://user-images.githubusercontent.com/77620925/154990755-1a1fa93e-54bf-4337-9658-3a59c7033eee.png)

**Comment by nvankampenhout** [comment]
Thanks, I updated the link.

Our open source plugins were moved to github a while ago. Links have been updated in the brXM 14 documentation only so pages for version 13 and older may still contain outdated links to code.onehippo.org. You can always check the brXM 14 version of the page for an up-to-date link.
