### ISSUE TITLE
xerces

### ISSUE THREAD

**Issue by machak** [bloomreach/docs-feedback#93]
https://xmdocumentation.bloomreach.com/14/library/upgrade-minor-versions/remove-apache-xerces.html

we might need to add

javax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl

**Comment by nvankampenhout** [comment]
Updated https://xmdocumentation.bloomreach.com/14/library/upgrade-minor-versions/remove-apache-xerces.html, thanks!
