### ISSUE TITLE
Links doesn`t work

### ISSUE THREAD

**Issue by ahalberkamp** [bloomreach/docs-feedback#94]
Hi,

On the page "https://xmdocumentation.bloomreach.com/13/library/upgrade-12-to-13/steps/miscellaneous-upgrade-steps.html" in the segment "Upgrade cmseditlink to manageContent tag" the links to the Migration of the cms-edit-link
doesn`t work (in Chrome/firefox).

Best regards Andi

**Comment by nvankampenhout** [comment]
Thanks Andi, I think you may have mistakenly inserted the wrong link and probably meant this page instead: https://xmdocumentation.bloomreach.com/13/library/upgrade-12-to-13/steps/drop-phased-out-features.html

I found all links on that page were broken for some reason and fixed them.

Thanks again for reporting this and have a great day!
