### ISSUE TITLE
Configure custom error page

### ISSUE THREAD

**Issue by MPriess** [bloomreach/docs-feedback#98]
The documentation contain some issues:

- The domain should be changed to http://api.{stack name}
- The "find file-id" example point to the wrong REST-API. HTML (503.html) files could be only uploaded as app configuration. So the example should point to /v3/appconfigfiles
- Use https in the example

https://xmdocumentation.bloomreach.com/bloomreach-cloud/reference-documentation/configure-custom-error-page.html

**Comment by nvankampenhout** [comment]
Thanks @MPriess , the page has been updated.
