### ISSUE TITLE
may or must? Use clear and consistent language. 

### ISSUE THREAD

**Issue by JasperFloorBloomreach** [bloomreach/docs-feedback#99]
https://xmdocumentation.bloomreach.com/library/upgrade-14-to-15/steps/rename-culturally-insensitive-terms.html

In the upgrade notes it mentions the change the usage of white/black to allow/block. For many of the items the wording is such that the rename is required, but two items leave this in doubt. 

- Renamed web.xml Context Parameter Name
   - it should be renamed 
- Renamed Configuration Files
   - The following configuration files have been renamed and may also be renamed in your project if it contains them.

This implies that it is optional.

- Public Java Constant Changes
    - may need to be renamed in your project, too, if your project makes use of them.
   
This is not optional in the text, but the text will be easy to confuse. Use clear language.

The other items use the following wording:

- will also have to be
- will have to be renamed as well.
- will have to be renamed as well.

So there is one use of the same wording, but in general each item finds a new way to say the same thing. While stylistically one might argue repeating the same wording is ugly, in this case it is technical instructions not literature. The wording should be equivalent and it should be clear if something is or isn't optional.

**Comment by nvankampenhout** [comment]
I agree and have changed them all to "must be renamed".
